project_id = "lkxrmjqrzhaivviuuamp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lkxrmjqrzhaivviuuamp.supabase.co"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.whatsapp-instance]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false

[functions.whatsapp-qrcode]
verify_jwt = true

[functions.process-rescue-messages]
verify_jwt = false

[functions.process-marketing-messages]
verify_jwt = false

[functions.bling-auth]
verify_jwt = false

[functions.bling-sync]
verify_jwt = true

[functions.bling-webhook]
verify_jwt = false

[functions.redirect-capture]
verify_jwt = false

[functions.process-flow-triggers]
verify_jwt = false

[functions.execute-flow-node]
verify_jwt = false

[functions.process-rede-payment]
verify_jwt = false

[functions.distribute-lead]
verify_jwt = false

[functions.dedupe-redirect-contacts]
verify_jwt = true

[functions.resend-initial-messages]
verify_jwt = false

[functions.meta-oauth]
verify_jwt = false

[functions.cloudapi-webhook]
verify_jwt = false

[functions.cloudapi-initiate-call]
verify_jwt = true

[functions.cloudapi-call-action]
verify_jwt = true

[functions.cloudapi-check-calling-status]
verify_jwt = true

[functions.cloudapi-enable-calling]
verify_jwt = true

[functions.bling-token-refresh]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.process-bulk-dispatch]
verify_jwt = false

[functions.test-marketing-campaign]
verify_jwt = false

[functions.sync-whatsapp-channels]
verify_jwt = false

[functions.cloudapi-send-message]
verify_jwt = true

[functions.whatsapp-embedded-signup]
verify_jwt = false

[functions.cloudapi-manual-connect]
verify_jwt = false

[functions.api-send-message]
verify_jwt = false

[functions.find-objection-context]
verify_jwt = false

[functions.cloudapi-register-phone]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = false

[functions.cloudapi-send-call-permission-request]
verify_jwt = true

[functions.reprocess-missed-triggers]
verify_jwt = false
