project_id = "lkxrmjqrzhaivviuuamp"

[functions.process-scheduled-messages]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.get-user-details]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-instance]
verify_jwt = false

[functions.meta-oauth]
verify_jwt = false

[functions.meta-sync]
verify_jwt = true

[functions.cleanup-webhook-logs]
verify_jwt = false

[functions.auto-assign-conversations]
verify_jwt = true

[functions.google-sheets-proxy]
verify_jwt = false

[functions.process-flow-delays]
verify_jwt = false

[functions.dispatch-webhook]
verify_jwt = true

[functions.register-session]
verify_jwt = false

[functions.distribute-lead]
verify_jwt = false

[functions.check-expiring-quotes]
verify_jwt = false

[functions.create-rede-payment]
verify_jwt = true

[functions.rede-webhook]
verify_jwt = false

[functions.calculate-shipping]
verify_jwt = false
