project_id = "lkxrmjqrzhaivviuuamp"

[functions.process-scheduled-messages]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.get-user-details]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false
