// Constantes fiscais para NF-e brasileira

export const ORIGEM_OPTIONS = [
  { value: '0', label: '0 - Nacional' },
  { value: '1', label: '1 - Estrangeira - Importação direta' },
  { value: '2', label: '2 - Estrangeira - Adquirida no mercado interno' },
  { value: '3', label: '3 - Nacional com conteúdo importação > 40%' },
  { value: '4', label: '4 - Nacional produção conforme processos básicos' },
  { value: '5', label: '5 - Nacional com conteúdo importação ≤ 40%' },
  { value: '6', label: '6 - Estrangeira - Importação direta sem similar' },
  { value: '7', label: '7 - Estrangeira - Mercado interno sem similar' },
  { value: '8', label: '8 - Nacional com conteúdo importação > 70%' },
];

export const CST_ICMS_OPTIONS = [
  { value: '00', label: '00 - Tributada integralmente' },
  { value: '10', label: '10 - Tributada com cobrança de ICMS por ST' },
  { value: '20', label: '20 - Com redução de base de cálculo' },
  { value: '30', label: '30 - Isenta/não tributada com cobrança de ICMS ST' },
  { value: '40', label: '40 - Isenta' },
  { value: '41', label: '41 - Não tributada' },
  { value: '50', label: '50 - Suspensão' },
  { value: '51', label: '51 - Diferimento' },
  { value: '60', label: '60 - ICMS cobrado anteriormente por ST' },
  { value: '70', label: '70 - Com redução de BC e cobrança de ICMS ST' },
  { value: '90', label: '90 - Outras' },
];

export const CSOSN_OPTIONS = [
  { value: '101', label: '101 - Tributada com permissão de crédito' },
  { value: '102', label: '102 - Tributada sem permissão de crédito' },
  { value: '103', label: '103 - Isenção do ICMS para faixa de receita bruta' },
  { value: '201', label: '201 - Tributada com permissão de crédito e ST' },
  { value: '202', label: '202 - Tributada sem permissão de crédito e ST' },
  { value: '203', label: '203 - Isenção do ICMS para faixa de receita bruta e ST' },
  { value: '300', label: '300 - Imune' },
  { value: '400', label: '400 - Não tributada pelo Simples Nacional' },
  { value: '500', label: '500 - ICMS cobrado anteriormente por ST ou antecipação' },
  { value: '900', label: '900 - Outros' },
];

export const CST_PIS_COFINS_OPTIONS = [
  { value: '01', label: '01 - Operação tributável (alíquota básica)' },
  { value: '02', label: '02 - Operação tributável (alíquota diferenciada)' },
  { value: '03', label: '03 - Operação tributável (alíquota por unidade)' },
  { value: '04', label: '04 - Operação tributável (monofásica - revenda zero)' },
  { value: '05', label: '05 - Operação tributável (ST)' },
  { value: '06', label: '06 - Operação tributável (alíquota zero)' },
  { value: '07', label: '07 - Operação isenta da contribuição' },
  { value: '08', label: '08 - Operação sem incidência da contribuição' },
  { value: '09', label: '09 - Operação com suspensão da contribuição' },
  { value: '49', label: '49 - Outras operações de saída' },
  { value: '50', label: '50 - Aquisição com direito a crédito (tributada)' },
  { value: '51', label: '51 - Aquisição com direito a crédito (não tributada)' },
  { value: '52', label: '52 - Aquisição com direito a crédito (exportação)' },
  { value: '53', label: '53 - Aquisição com direito a crédito (tributada e não tributada)' },
  { value: '54', label: '54 - Aquisição com direito a crédito (tributada e exportação)' },
  { value: '55', label: '55 - Aquisição com direito a crédito (não tributada e exportação)' },
  { value: '56', label: '56 - Aquisição com direito a crédito (vinculada a receitas)' },
  { value: '60', label: '60 - Crédito presumido (operação tributável)' },
  { value: '61', label: '61 - Crédito presumido (operação não tributável)' },
  { value: '62', label: '62 - Crédito presumido (operação de exportação)' },
  { value: '63', label: '63 - Crédito presumido (tributável e não tributável)' },
  { value: '64', label: '64 - Crédito presumido (tributável e exportação)' },
  { value: '65', label: '65 - Crédito presumido (não tributável e exportação)' },
  { value: '66', label: '66 - Crédito presumido (vinculada a receitas de exportação)' },
  { value: '67', label: '67 - Crédito presumido (outras operações)' },
  { value: '70', label: '70 - Operação de aquisição sem direito a crédito' },
  { value: '71', label: '71 - Operação de aquisição com isenção' },
  { value: '72', label: '72 - Operação de aquisição com suspensão' },
  { value: '73', label: '73 - Operação de aquisição com alíquota zero' },
  { value: '74', label: '74 - Operação de aquisição sem incidência' },
  { value: '75', label: '75 - Operação de aquisição por substituição' },
  { value: '98', label: '98 - Outras operações de entrada' },
  { value: '99', label: '99 - Outras operações' },
];

export const CST_IPI_OPTIONS = [
  { value: '00', label: '00 - Entrada com recuperação de crédito' },
  { value: '01', label: '01 - Entrada tributável com alíquota zero' },
  { value: '02', label: '02 - Entrada isenta' },
  { value: '03', label: '03 - Entrada não tributada' },
  { value: '04', label: '04 - Entrada imune' },
  { value: '05', label: '05 - Entrada com suspensão' },
  { value: '49', label: '49 - Outras entradas' },
  { value: '50', label: '50 - Saída tributada' },
  { value: '51', label: '51 - Saída tributável com alíquota zero' },
  { value: '52', label: '52 - Saída isenta' },
  { value: '53', label: '53 - Saída não tributada' },
  { value: '54', label: '54 - Saída imune' },
  { value: '55', label: '55 - Saída com suspensão' },
  { value: '99', label: '99 - Outras saídas' },
];

export const UNIDADE_COMERCIAL_OPTIONS = [
  { value: 'UN', label: 'UN - Unidade' },
  { value: 'PC', label: 'PC - Peça' },
  { value: 'CX', label: 'CX - Caixa' },
  { value: 'KG', label: 'KG - Quilograma' },
  { value: 'G', label: 'G - Grama' },
  { value: 'LT', label: 'LT - Litro' },
  { value: 'ML', label: 'ML - Mililitro' },
  { value: 'M', label: 'M - Metro' },
  { value: 'M2', label: 'M² - Metro quadrado' },
  { value: 'M3', label: 'M³ - Metro cúbico' },
  { value: 'PAR', label: 'PAR - Par' },
  { value: 'DZ', label: 'DZ - Dúzia' },
  { value: 'CT', label: 'CT - Cartela' },
  { value: 'FD', label: 'FD - Fardo' },
  { value: 'PCT', label: 'PCT - Pacote' },
  { value: 'RL', label: 'RL - Rolo' },
  { value: 'SC', label: 'SC - Saco' },
  { value: 'BD', label: 'BD - Balde' },
  { value: 'JG', label: 'JG - Jogo' },
  { value: 'KT', label: 'KT - Kit' },
];

export const TIPO_PRODUTO_OPTIONS = [
  { value: '00', label: '00 - Mercadoria para Revenda' },
  { value: '01', label: '01 - Matéria-Prima' },
  { value: '02', label: '02 - Embalagem' },
  { value: '03', label: '03 - Produto em Processo' },
  { value: '04', label: '04 - Produto Acabado' },
  { value: '05', label: '05 - Subproduto' },
  { value: '06', label: '06 - Produto Intermediário' },
  { value: '07', label: '07 - Material de Uso e Consumo' },
  { value: '08', label: '08 - Ativo Imobilizado' },
  { value: '09', label: '09 - Serviços' },
  { value: '10', label: '10 - Outros insumos' },
  { value: '99', label: '99 - Outras' },
];

export const REGIME_TRIBUTARIO_OPTIONS = [
  { value: 'simples_nacional', label: 'Simples Nacional' },
  { value: 'lucro_presumido', label: 'Lucro Presumido' },
  { value: 'lucro_real', label: 'Lucro Real' },
];

export const CFOP_VENDA_OPTIONS = [
  { value: '5101', label: '5101 - Venda de prod. industrialização própria (UF)' },
  { value: '5102', label: '5102 - Venda de mercadoria adquirida (UF)' },
  { value: '5103', label: '5103 - Venda produção sob encomenda (UF)' },
  { value: '5104', label: '5104 - Venda produção estab. para industrialização (UF)' },
  { value: '5105', label: '5105 - Venda produção estab. a comerc. não contrib. (UF)' },
  { value: '5106', label: '5106 - Venda mercadoria adq. para industrialização (UF)' },
  { value: '5401', label: '5401 - Venda produção com ST (UF)' },
  { value: '5403', label: '5403 - Venda mercadoria adq. com ST (UF)' },
  { value: '5405', label: '5405 - Venda mercadoria ST em operação com ME/EPP (UF)' },
  { value: '5929', label: '5929 - Lançamento NFC-e (UF)' },
  { value: '6101', label: '6101 - Venda de prod. industrialização própria (Fora UF)' },
  { value: '6102', label: '6102 - Venda de mercadoria adquirida (Fora UF)' },
  { value: '6103', label: '6103 - Venda produção sob encomenda (Fora UF)' },
  { value: '6104', label: '6104 - Venda produção estab. para industrialização (Fora UF)' },
  { value: '6105', label: '6105 - Venda produção estab. a comerc. não contrib. (Fora UF)' },
  { value: '6106', label: '6106 - Venda mercadoria adq. para industrialização (Fora UF)' },
  { value: '6401', label: '6401 - Venda produção com ST (Fora UF)' },
  { value: '6403', label: '6403 - Venda mercadoria adq. com ST (Fora UF)' },
];
